# Generated by Django 3.1 on 2020-08-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp_score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibhu_score', models.IntegerField(blank=True, default=0)),
                ('dad_score', models.IntegerField(blank=True, default=0)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='pp_score.session')),
            ],
        ),
    ]
