# Generated by Django 3.1 on 2020-08-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp_score', '0002_auto_20200830_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='winner',
            field=models.IntegerField(choices=[(1, 'Vibhu'), (2, 'Dad'), (3, 'Draw')], default=3),
        ),
    ]
